# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Infinity Hugo"
license = "MIT"
licenselink = "https://github.com/gethugothemes/infinity-hugo/blob/master/LICENSE"
description = "Infinity is a responsive, modern and clean free coming soon landing page theme for Hugo."
homepage = "https://gethugothemes.com/products/infinity/"
demosite = "https://demo.gethugothemes.com/infinity/"
tags = ['comming-soon', 'landing-page', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap4', 'gethugothemes']
features = ['bootstrap4','responsive']
min_version = "0.64.0"

[author]
  name = "Gethugothemes"
  homepage = "https://gethugothemes.com/"
